USE [master]
GO
/****** Object:  Database [apikeycurrency]    Script Date: 17/04/2023 16:32:00 ******/
CREATE DATABASE [apikeycurrency]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'apikeycurrency', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\apikeycurrency.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'apikeycurrency_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\apikeycurrency_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [apikeycurrency] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [apikeycurrency].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [apikeycurrency] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [apikeycurrency] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [apikeycurrency] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [apikeycurrency] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [apikeycurrency] SET ARITHABORT OFF 
GO
ALTER DATABASE [apikeycurrency] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [apikeycurrency] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [apikeycurrency] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [apikeycurrency] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [apikeycurrency] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [apikeycurrency] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [apikeycurrency] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [apikeycurrency] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [apikeycurrency] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [apikeycurrency] SET  ENABLE_BROKER 
GO
ALTER DATABASE [apikeycurrency] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [apikeycurrency] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [apikeycurrency] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [apikeycurrency] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [apikeycurrency] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [apikeycurrency] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [apikeycurrency] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [apikeycurrency] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [apikeycurrency] SET  MULTI_USER 
GO
ALTER DATABASE [apikeycurrency] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [apikeycurrency] SET DB_CHAINING OFF 
GO
ALTER DATABASE [apikeycurrency] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [apikeycurrency] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [apikeycurrency] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [apikeycurrency] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [apikeycurrency] SET QUERY_STORE = OFF
GO
USE [apikeycurrency]
GO
/****** Object:  Table [dbo].[apikey]    Script Date: 17/04/2023 16:32:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[apikey](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[apikey] [nvarchar](60) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[apiportfolioIDs]    Script Date: 17/04/2023 16:32:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[apiportfolioIDs](
	[id] [nvarchar](100) NULL,
	[coinid] [nvarchar](10) NULL
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[apikey] ON 
GO
INSERT [dbo].[apikey] ([id], [apikey]) VALUES (1, N'da1f96d7-f9f1-476a-a9e9-4500c5cee0bb')
GO
SET IDENTITY_INSERT [dbo].[apikey] OFF
GO
INSERT [dbo].[apiportfolioIDs] ([id], [coinid]) VALUES (N'63feda8ad0a19758f3bde124', N'1')
GO
INSERT [dbo].[apiportfolioIDs] ([id], [coinid]) VALUES (N'605e2ce9d41eae1066535f7c', N'1027')
GO
INSERT [dbo].[apiportfolioIDs] ([id], [coinid]) VALUES (N'625d04fa57c0560770d004e1', N'825, 4687')
GO
INSERT [dbo].[apiportfolioIDs] ([id], [coinid]) VALUES (N'61213ce7c049672cb6ce7eb8', N'2010')
GO
USE [master]
GO
ALTER DATABASE [apikeycurrency] SET  READ_WRITE 
GO
